/**
 * Defines standard audit event types across the Novamind platform.
 */
export enum AuditEventType {
  // Authentication Events
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_MFA_SETUP = 'USER_MFA_SETUP',
  USER_MFA_VERIFY_SUCCESS = 'USER_MFA_VERIFY_SUCCESS',
  USER_MFA_VERIFY_FAILURE = 'USER_MFA_VERIFY_FAILURE',
  USER_PASSWORD_RESET_REQUEST = 'USER_PASSWORD_RESET_REQUEST',
  USER_PASSWORD_RESET_SUCCESS = 'USER_PASSWORD_RESET_SUCCESS',
  USER_SESSION_RENEWED = 'USER_SESSION_RENEWED',
  USER_SESSION_RENEWAL_FAILED = 'USER_SESSION_RENEWAL_FAILED',
  USER_SESSION_EXPIRED = 'USER_SESSION_EXPIRED',
  USER_SESSION_VALIDATED = 'USER_SESSION_VALIDATED',
  USER_SESSION_VALIDATION_FAILED = 'USER_SESSION_VALIDATION_FAILED',
  USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED',
  USER_SESSION_TIMEOUT_WARNING = 'USER_SESSION_TIMEOUT_WARNING',
  USER_SESSION_TIMEOUT_IDLE = 'USER_SESSION_TIMEOUT_IDLE',
  USER_SESSION_EXTENDED_MANUALLY = 'USER_SESSION_EXTENDED_MANUALLY',

  // Patient Data Events
  PATIENT_CREATED = 'PATIENT_CREATED',
  PATIENT_VIEWED = 'PATIENT_VIEWED',
  PATIENT_UPDATED = 'PATIENT_UPDATED',
  PATIENT_DELETED = 'PATIENT_DELETED',
  PATIENT_RECORD_ACCESSED = 'PATIENT_RECORD_ACCESSED',
  PATIENT_PHI_EXPORTED = 'PATIENT_PHI_EXPORTED',

  // Clinical Record Events
  CLINICAL_RECORD_CREATED = 'CLINICAL_RECORD_CREATED',
  CLINICAL_RECORD_UPDATED = 'CLINICAL_RECORD_UPDATED',
  CLINICAL_RECORD_DELETED = 'CLINICAL_RECORD_DELETED',

  // Brain Model & Visualization Events
  BRAIN_MODEL_GENERATED = 'BRAIN_MODEL_GENERATED',
  BRAIN_MODEL_VIEWED = 'BRAIN_MODEL_VIEWED',
  BRAIN_MODEL_ANALYSIS_RUN = 'BRAIN_MODEL_ANALYSIS_RUN',
  BRAIN_VISUALIZATION_INTERACTION = 'BRAIN_VISUALIZATION_INTERACTION',

  // ML Operations
  ML_PREDICTION_REQUEST = 'ML_PREDICTION_REQUEST',
  ML_PREDICTION_SUCCESS = 'ML_PREDICTION_SUCCESS',
  ML_PREDICTION_FAILURE = 'ML_PREDICTION_FAILURE',
  ML_PHI_DETECTED = 'ML_PHI_DETECTED',
  ML_PHI_REDACTED = 'ML_PHI_REDACTED',

  // System & Security Events
  SYSTEM_CONFIG_CHANGED = 'SYSTEM_CONFIG_CHANGED',
  SECURITY_ALERT_TRIGGERED = 'SECURITY_ALERT_TRIGGERED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  API_RATE_LIMIT_EXCEEDED = 'API_RATE_LIMIT_EXCEEDED',

  // Add other specific events as needed
  THEME_CHANGED = 'THEME_CHANGED', // Example for ThemeProvider
} 